In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from imblearn.over_sampling import SMOTE
from pandas.plotting import parallel_coordinates,scatter_matrix
import seaborn as sns
import os
import matplotlib.pyplot as plt
import re

In [33]:
#To be sure that we get all the right keys
CSV_KEYS = ['id', 'class']
for i in range(10):
    CSV_KEYS.append('hotkey' + str(i))

#Define map class->value
CLASSES = {}

#Zerg -> 0
#Protoss -> 1
#Terran -> 2
CLASSES['Zerg'] = 0
CLASSES['Protoss'] = 1
CLASSES['Terran'] = 2

#Define Directories
OUTPUT = '../data/output'
OUTPUT_SUB = OUTPUT
OUTPUT_CHARTS = OUTPUT + '/charts/'
INPUT = '../data/input'
INPUT_TRAIN = INPUT + '/TRAIN.CSV'
INPUT_TEST = INPUT + '/TEST.CSV'
INPUT_TRAIN_LONG = INPUT + '/TRAIN_LONG.CSV'

#Define Parameters to test minimun amount of data
NM_PARTIES = 4

In [22]:
import csv
from collections import defaultdict

def get_train_data(csv_file=INPUT_TRAIN, up_to=10, num_parties=4):    
    with open(csv_file, newline='') as csv_text:
        cvs_reader = csv.reader(csv_text, delimiter=',')
        data = []

        for row in cvs_reader:
            #Voir si on a deja suffisament de parties
            count = 0
            for party in data:
                if party['id'] == row[0]:
                    count += 1
            if count >= num_parties:
                continue
            #Prendre les donnes
            train_dict = defaultdict(int)
            train_dict['id'] = row[0]
            train_dict['class'] = row[1]

            t = 0
            idx = 0
            
            for i in range(2, len(row)):
                if 't' in row[i][0] and int(row[i][1:]) == up_to:
                    idx = i
                    break
                    
                    
            for i in range(2, idx):
                if 'hotkey' in row[i]:
                    train_dict[row[i][:-1]] += 1/up_to
                    
            data.append(train_dict)
            
        
        return data

def zero_dict():
    new_dict = {}
    #Initialize to zero
    for i in CSV_KEYS:
        new_dict[i] = 0
    return new_dict

In [26]:
data= get_train_data(num_parties=1)
df = pd.DataFrame(data, columns=CSV_KEYS) 
print('Shape of the dataset: ' + str(df.shape))
df.sample(n=5).fillna(0)

Shape of the dataset: (200, 12)

,id,class,hotkey0,hotkey1,hotkey2,hotkey3,hotkey4,hotkey5,hotkey6,hotkey7,hotkey8,hotkey9
62,http://us.battle.net/sc2/en/profile/3948354/1/...,Zerg,0.0,0.4,0.0,0.3,0.0,0.0,0.0,0.0,0.0,0.0
171,http://us.battle.net/sc2/en/profile/4352638/1/...,Protoss,0.0,0.0,0.0,0.0,0.1,0.3,0.1,0.0,0.0,0.0
115,http://kr.battle.net/sc2/en/profile/2343067/1/...,Protoss,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
90,http://us.battle.net/sc2/en/profile/2821952/1/...,Zerg,0.0,0.1,0.1,0.5,0.9,0.1,0.1,0.0,0.0,0.0
95,http://kr.battle.net/sc2/en/profile/2343479/1/...,Zerg,0.0,0.0,1.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0

In [35]:
df['count'] = df.groupby('id').id.transform('count')
df = df.drop(df[df.count < NM_PARTIES].index)
df

,id,class,hotkey0,hotkey1,hotkey2,hotkey3,hotkey4,hotkey5,hotkey6,hotkey7,hotkey8,hotkey9,count
0,http://eu.battle.net/sc2/en/profile/4234852/1/...,Protoss,0.1,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,NaN,1
1,http://eu.battle.net/sc2/en/profile/3074362/1/...,Protoss,NaN,NaN,NaN,0.6,NaN,NaN,NaN,NaN,NaN,NaN,1
2,http://eu.battle.net/sc2/en/profile/3401218/1/...,Protoss,NaN,NaN,NaN,NaN,0.1,NaN,NaN,NaN,NaN,NaN,1
3,http://eu.battle.net/sc2/en/profile/2896854/1/...,Terran,0.1,NaN,NaN,1.2,NaN,NaN,NaN,NaN,NaN,NaN,1
4,http://eu.battle.net/sc2/en/profile/3538115/1/...,Zerg,1.5,0.1,NaN,NaN,NaN,NaN,1.5,NaN,NaN,0.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,http://xx.battle.net/sc2/en/profile/406/1/INno...,Terran,NaN,NaN,NaN,NaN,NaN,NaN,0.8,NaN,NaN,NaN,1
196,http://xx.battle.net/sc2/en/profile/410/1/STBo...,Terran,NaN,0.7,0.7,0.1,0.1,0.1,0.1,NaN,NaN,NaN,1
197,http://xx.battle.net/sc2/en/profile/407/1/NaNiwa/,Protoss,NaN,NaN,NaN,0.4,NaN,NaN,NaN,NaN,NaN,NaN,1
198,http://xx.battle.net/sc2/en/profile/401/1/Soul...,Zerg,NaN,NaN,1.0,NaN,1.6,NaN,NaN,NaN,NaN,NaN,1
199,http://xx.battle.net/sc2/en/profile/405/1/MMA/,Terran,0.1,0.1,0.6,0.1,0.1,0.1,0.1,0.1,0.1,0.1,1